### ISSUE TITLE
Idling to sleep is prevented under both 10.6 and 10.7 in 32-bit mode

### ISSUE THREAD

**Issue by Goldfish64** [RehabMan/OS-X-ACPI-Battery-Driver#14]
After installing the kext (compiled for 32-bit mode) under either 10.6 and 10.7 on a Dell Inspiron 1520, automatic sleep doesn't work anymore. Sleep itself still works. 64-bit mode is untested as the laptop has GMA X3100 and thus requires a 32-bit kernel. I'm currently running a fully updated 10.6.8 install.

**Comment by RehabMan** [comment]
Won't fix.  I'm not supporting extremely old hardware, nor custom builds of the kext.
If you build the kext for your own purposes,  it is your responsibility to fix any issues.
