### ISSUE TITLE
battery not charge, even boot to windows

### ISSUE THREAD

**Issue by BennyWang** [RehabMan/OS-X-ACPI-Battery-Driver#18]
I patched dsdt and install AcpiBatteryManager.kext, battery status is shown, but when adaper plug in, It's show battery not charge, from log, I found the charging bit never set, unplug in status is 1, plug in status is 0.

dig into dsdt，I found it just set PCI0.LPCB.EC0.MBST to status word.

If I reset EC, and boot to windows, then battery charge again, but once if I have boot macos, then back to windows, battery not charge again.
I dont know what cause this happen, blow is my _BST/UPBS/IVBS.

Method (_BST, 0, NotSerialized)
            {
                If (LEqual (^^PCI0.LPCB.EC0.ECOK, One))
                {
                    If (^^PCI0.LPCB.EC0.MBTS)
                    {
                        UPBS ()
                    }
                    Else
                    {
                        IVBS ()
                    }
                }
                Else
                {
                    IVBS ()
                }

                If (LEqual (BRTE, Zero))
                {
                    Store (0xFFFFFFFF, Index (PBST, One))
                }

                Return (PBST)
            }

Method (IVBS, 0, NotSerialized)
            {
                Store (Zero, Index (PBST, Zero))
                Store (0xFFFFFFFF, Index (PBST, One))
                Store (0xFFFFFFFF, Index (PBST, 0x02))
                Store (0x2710, Index (PBST, 0x03))
            }
            Method (UPBS, 0, NotSerialized)
            {
                Store (B1B2(^^PCI0.LPCB.EC0.CUR0, ^^PCI0.LPCB.EC0.CUR1), Local0)
                If (And (Local0, 0x8000))
                {
                    If (LEqual (Local0, 0xFFFF))
                    {
                        Store (0xFFFFFFFF, Index (PBST, One))
                    }
                    Else
                    {
                        Not (Local0, Local1)
                        Increment (Local1)
                        And (Local1, 0xFFFF, Local3)
                        Store (Local3, Index (PBST, One))
                    }
                }
                Else
                {
                    Store (Local0, Index (PBST, One))
                }
                Store (B1B2(^^PCI0.LPCB.EC0.BRM0, ^^PCI0.LPCB.EC0.BRM1), Local5)
                If (LNot (And (Local5, 0x8000)))
                {
                    ShiftRight (Local5, 0x05, Local5)
                    ShiftLeft (Local5, 0x05, Local5)
                    If (LNotEqual (Local5, DerefOf (Index (PBST, 0x02))))
                    {
                        Store (Local5, Index (PBST, 0x02))
                    }
                }
                If (LAnd (LNot (^^PCI0.LPCB.EC0.SW2S), LEqual (^^PCI0.LPCB.EC0.BACR, One)))
                {
                    Store (FABL, Index (PBST, 0x02))
                }
                Store (B1B2(^^PCI0.LPCB.EC0.BCV0, ^^PCI0.LPCB.EC0.BCV1), Index (PBST, 0x03))
                Store (^^PCI0.LPCB.EC0.MBST, Index (PBST, Zero))
            }

**Comment by RehabMan** [comment]
DSDT issues are not issues with this kext.
You should use the forums.
