### ISSUE TITLE
Menu Bar power indicator doesn't update in High Sierra

### ISSUE THREAD

**Issue by coolstar** [RehabMan/OS-X-ACPI-Battery-Driver#19]
The menu bar power indicator doesn't update the battery/power status properly in High Sierra. (Works fine in Sierra).

The ACPI itself is working fine, as coconutBattery updates fine when the device is plugged in/unplugged and the battery percentage changes, even in High Sierra.

**Comment by Andrey1970AppleLife** [comment]
Yes, this problem only with the version battery kext by RehabMan.

**Comment by tluck** [comment]
FYI I use this kext and see charge level indicated for me on High Sierra - for my Lenovo T420 and my Dell M4800.

**Comment by coolstar** [comment]
Looks like updating to macOS High Sierra beta 7 from beta 4 (haven't tried beta 5 or 6 as I temporarily went back to Sierra) fixed this issue!
