### ISSUE TITLE
Low battery warning with 1.81.2 Sierra

### ISSUE THREAD

**Issue by srscott** [RehabMan/OS-X-ACPI-Battery-Driver#22]
Kext installed to S/L/E
DSDT appropriately patched
Kext working perfectly in High Sierra
Kext in Sierra displays the battery percentage correctly but gives a low battery warning.

![screen shot 2017-09-01 at 11 14 00 am](https://user-images.githubusercontent.com/17326832/29952311-bc81daee-8f07-11e7-9c07-8d7c048c2174.png)

![screen shot 2017-09-01 at 11 24 24 am](https://user-images.githubusercontent.com/17326832/29952380-28e367f2-8f08-11e7-8694-62a561825e11.png)

[DSDT.aml.zip](https://github.com/RehabMan/OS-X-ACPI-Battery-Driver/files/1268932/DSDT.aml.zip)

**Comment by RehabMan** [comment]
I have this happening intermittently as well.
It happens only when booting on battery, not when AC is plugged (important data to mention).

I will probably need to make more of the 10.13 changes conditional such that the old code path is taken prior to 10.13.

You can install an older version on 10.12 in the interim.

**Comment by RehabMan** [comment]
Try ACPIBatteryManager v1.81.3

**Comment by srscott** [comment]
ACPIBatteryManager v1.81.3 has resolved the issue.

**Comment by RehabMan** [comment]
Seems fixed then.
Closing.
