### ISSUE TITLE
Low battery warning and wrong percentage with 1.81.3 Sierra 

### ISSUE THREAD

**Issue by diaafares** [RehabMan/OS-X-ACPI-Battery-Driver#23]
Hi,
I have two problems with ACPIBatteryManager,
the first is that I have 5% difference in battery percentage between macOS and Windows multi boot, so if the battery is 40% under Windows 10 it appears as 45% at macOS 10.12.6

the second problem is that it gives a low battery warning even is the battery more than 90% !!!
My laptop is Lenovo ThinkPad e560, Intel Core i5 6200U and here is my CLOVER folder that I use and the IOREG-file
[For Rehebman.zip](https://github.com/RehabMan/OS-X-ACPI-Battery-Driver/files/1278692/For.Rehebman.zip)

**Comment by RehabMan** [comment]
Use the forums:
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
