### ISSUE TITLE
Does not work Slightly dim the display while on battery power. (10.13)

### ISSUE THREAD

**Issue by Andrey1970AppleLife** [RehabMan/OS-X-ACPI-Battery-Driver#24]
Does not work Slightly dim the display while on battery power. (10.13)
Starts working only after turn OFF and turn ON checkbox "Slightly dim the display while on battery power".
v1.81.3

**Comment by RehabMan** [comment]
Use the forums:
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
