### ISSUE TITLE
Couldnt show battery when startup...

### ISSUE THREAD

**Issue by gujiangjiang** [RehabMan/OS-X-ACPI-Battery-Driver#26]
With the new kext it couldnt show battert icon when startup and must showit by myself and when restart it still disappear.

Old kext dont have this problem..

**Comment by gujiangjiang** [comment]
I have emu+rc and nvram works but it still dont show icon when startup...

**Comment by Shinji3rd** [comment]
I have this exact same problem.

**Comment by TrungNguyen1909** [comment]
It also fail to update battery charge in realtime.

**Comment by mrvir** [comment]
I have the same problem.
macOS 10.13.1 using the latest version of this kext.

**Comment by Shinji3rd** [comment]
I saw that if you wait a couple of seconds before entering the password at the login screen, the battery level suddenly appear and it works. But if you enter the password immediately after boot without giving time, the battery level does not appear and you have to enable it manually.

**Comment by TrungNguyen1909** [comment]
Try this! Worked for me!!!
[ACPIBatteryManager.kext.zip](https://github.com/RehabMan/OS-X-ACPI-Battery-Driver/files/1576112/ACPIBatteryManager.kext.zip)

**Comment by RehabMan** [comment]
Use the forums for troubleshooting.
