### ISSUE TITLE
Laptop not charging

### ISSUE THREAD

**Issue by berkayakin** [RehabMan/OS-X-ACPI-Battery-Driver#27]
Hi, I have HP Pavilion 15-bc207nl I used HP-Pavilion-n012tx patch which is the closest to my model, and I also use your battery kext. My battery has been recognized by the OS and the percentage is true but my laptop is not charging when Hackintosh is on. Is it about incorrect DSDT patch or something else?

Also I will be very very glad if you can make a DSDT patch for HP Pavilion 15-bc207nl.

Thanks!

**Comment by RehabMan** [comment]
Use the forums.
Link is provided in the README.
