### ISSUE TITLE
22 Seconds Delay when power adapter is disconnected

### ISSUE THREAD

**Issue by najdanovicivan** [RehabMan/OS-X-ACPI-Battery-Driver#32]
I am experiencing an issue when power adapter is disconnected. 

Charging state is automatically updated
It takes around 22 Seconds to switch Power source from "Power Adapter" to "Battery"

I use Lenovo X220

I have patched EC Multibyte and added BATC changing all the Notif methods to BATC 

Additionally I had to patch device(AC) in order for ACPIACAdapter to be loadded by adding 
Name (_PWR, Package (){0x18, 0x3})

Can this issue be related to DSDT or it is a bug in Driver ?

When it runs on battery and AC adapter is connected status icon is updated automatically

OSX Version is 10.14 Mojave Public Beta (18A389)

**Comment by RehabMan** [comment]
No need to patch Device(AC).  This kext has its own ACPI handler for AC adapter.
You should use the forums for troubleshooting anyway.
