### ISSUE TITLE
Force refresh on all batteries

### ISSUE THREAD

**Issue by JayMonkey** [RehabMan/OS-X-ACPI-Battery-Driver#5]
Hi RM,

As requested here :-

http://www.tonymacx86.com/mountain-lion-laptop-support/69472-battery-manager-fix-boot-without-batteries-58.html#post784853

When running dual batteries the battery menu icon % very often stalls and fails to update when discharging from (BAT2), manually forcing a refresh by de-selecting & re-selecting  "Show Percentage" via the battery context menu usually updates the menu %. Once the laptop switches  to discharging from BAT1 the menu % seems to update ok.

For further details on this issue see my post here:-

http://www.tonymacx86.com/mavericks-laptop-support/114961-jays-monkeybook-pro-ultimate-sony-vpc-se-customac-build-51.html#post782440

As discussed I believe that most of these issues are caused by a bug in the OSX battery monitor process. However you suggested that it may be possible to force an update on all batteries from within your kext:-

http://www.tonymacx86.com/mountain-lion-laptop-support/69472-battery-manager-fix-boot-without-batteries-58.html#post784587

Let me know if i can be of any further help when/if you come to address this issue.

Cheers
Jay

**Comment by RehabMan** [comment]
It appears multi-battery support has been significantly altered or removed in Yosemite.

Won't fix.
