### ISSUE TITLE
Issue with ACPI-Battery

### ISSUE THREAD

**Issue by Vmonheros** [RehabMan/OS-X-ACPI-Battery-Driver#7]
I use your last BatteryManager kext (download from here) and I encounter an "issue" with it about the battery status icon.

When I'm charging the battery, normal icon (the battery with the "power" inside). However, when the battery is finished to be charge, the battery icon change to the default battery one - the one you've got in fact when you're on battery (and normally discharging it) remaining at 100% charge (and when I check the status, it says that the power is coming from battery, not from wall plug). So, the icon didn't change to the normal "electrical plug" one. It is the same if I remove the charger, let the battery discharge only few % (I know that in this case, battery will not charge after to avoid "memory" ) and plug again the transformer on the laptop, the battery icon doesn't change and remain "on battery"... However, for sure, battery % didn't decrease...

I don't have this behavior (in fact I've got the normal one) with the Zprood kext (the old from) from here http://www.insanelymac.com/forum/topic/272...nager-for-lion/. However, this kext is not able to read correctly battery count cycle for my battery.

So, can I help you to track this ?

Thanks.

Fred.

P.S.: I've got an Asus Zenbook UX32LN patched with your MacIASL "repository" change 4.08. I can forward you my patched DSDT and SSDTs if necessary.

**Comment by dhnguyen92** [comment]
Can you add this to your DSDT patch repo? I saw many laptops with same problem.

**Comment by RehabMan** [comment]
Not possible to create a generic patch.  It will always be DSDT/machine specific.

**Comment by klydra** [comment]
Hey @RehabMan ,
I experienced the same issue. 
Could you help me too? I provided the information according to your battery patching guide. 
[report.zip](https://github.com/RehabMan/OS-X-ACPI-Battery-Driver/files/2812442/report.zip)

**Comment by RehabMan** [comment]
Requires analysis of your battery related code in ACPI.
