### ISSUE TITLE
Battery on 10.10.3

### ISSUE THREAD

**Issue by walkman8196** [RehabMan/OS-X-ACPI-Battery-Driver#9]
Hello RehabMan.
I use your kext and dsdt patch (battery_HP-DV7-6xxx.txt) for the battery
Before version 10.10.3 everything worked perfectly. 
(The indicator does not appear or does not work at all)
And this problem still occurs in some people.

You can see what is the reason?
I can provide reports on demand.

**Comment by bySabi** [comment]
Same problem here with 10.10.3.

**Comment by RehabMan** [comment]
Post ioreg and logs from system.log (with debug version).

**Comment by walkman8196** [comment]
https://cloud.mail.ru/public/7nhSJL994Swj/system.log
https://cloud.mail.ru/public/5fwYoSUXrJ55/MacBook%20Pro%C2%A0%E2%80%94%20%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD.ioreg

**Comment by RehabMan** [comment]
Your DSDT is reporting that battery is not present:
[code]
Apr 26 09:06:52 localhost kernel[0]: AppleSmartBattery::setBatterySTA: battery_status = 0xf
Apr 26 09:06:52 localhost kernel[0]: AppleSmartBattery: !fBatteryPresent
[/code]

_STA should report 0x1F when battery is installed.  Refer to ACPI spec.

**Comment by walkman8196** [comment]
new ioreg from 2.1 and a new log
I ran the laptop on battery without AC adapter but in the log still battery_status = 0xf
https://cloud.mail.ru/public/4QVmKmtGi7PA/data.zip

**Comment by RehabMan** [comment]
You have DSDT issues.  You probably need patches.  Read/follow my guide: http://www.tonymacx86.com/yosemite-laptop-support/116102-guide-how-patch-dsdt-working-battery-status.html

**Comment by RehabMan** [comment]
Note also that ACPIDebug.kext can be useful for debugging DSDT problems: https://github.com/RehabMan/OS-X-ACPI-Debug

**Comment by walkman8196** [comment]
Rehabman Hello, thanks for the advice.
did not look for the cause, took a clean patch dsdt Hpet and battery, start, and it worked.
Thanks for the advice,
and for your time
